### ISSUE TITLE
Remove Guzzle 6

### ISSUE THREAD

**Issue by StudioMaX** [Payum/OmnipayV3Bridge#11]
I just remembered that Guzzle 7 is incompatible with `php-http/guzzle6-adapter`.
Maybe it is easier to release a new major version of `payum/omnipay-v3-bridge`, in which the requirement of `guzzlehttp/guzzle` and `php-http/guzzle6-adapter` is removed. And instead add a suggest section in composer.json indicating the need to install any compatible [Http Client](https://docs.php-http.org/en/latest/clients.html) like:
``
composer require payum/omnipay-v3-bridge php-http/guzzle7-adapter
``

**Comment by belmeopmenieuwesim** [comment]
When will this be removed from `composer.json`? It is not used at all in this repo and it restricts my current project.

**Comment by belmeopmenieuwesim** [comment]
Especially since latest `league/omnipay` requires `php-http/guzzle7-adapter: ^1`, which requires `guzzlehttp/guzzle:^7`. So it is currently broken to be used with the latest omnipay V3.

**Comment by StudioMaX** [comment]
Unfortunately, just removing `php-http/guzzle6-adapter` from `composer.json` will not be enough, as this will break BC. Some of the maintainers will need to release a new major version of `payum/omnipay-v3-bridge`.
> Especially since latest league/omnipay requires php-http/guzzle7-adapter: ^1, which requires guzzlehttp/guzzle:^7.

Actually, `payum/omnipay-v3-bridge` does not require `league/omnipay`, but `omnipay/common`. So theoretically you can use any other HttpClient, not just `php-http/guzzle7-adapter`.  But anyway, currently required `php-http/guzzle6-adapter` breaks dependency chain with other libraries since it requires an unmaintained `guzzlehttp/guzzle:^6`.

**Comment by pierredup** [comment]
I think we can actually remove the dependency on Guzzle completely, and just require `php-http/client-implementation`. Then it is up to the user to decide which adapter to use (So anyone can use Guzzle 6 or 7, or any other implementation).

This might break BC, especially for someone that doesn't explicitly require a php-http implementation (because they might have gotten Guzzle 6 by default through this package). But I think the error message during the composer install should be clear enough, and we can even add Guzzle to the `suggests` part of the composer file.

**Comment by pierredup** [comment]
Fixed in #12
